### ISSUE TITLE
Issue with image_process

### ISSUE THREAD

**Issue by Trulaug** [Daggy1234/dagpi-image#53]
Whenever using img = await dagpi.image_process(ImageFeatures.delete(), url , url2) an exception is raised TypeError: image_process() takes 3 positional arguments but 4 were given. When removing url2 an exception is raised that url2 is missing

**Comment by daggy1234** [comment]
Okay 3 things

1) You need to initialise the client. So `asyncdagpi.Client("token")`, then call image process on the initialized client

2) `url2` is a kwarg. It needs to be passed in like so

```py
dagpi = asyncdagpi.Client("")
await dagpi.image_process(ImageFeatures.delete(), "url", url2="url2")
```

3) Docs have it all

asyncdagpi.rtfd.io/

**Comment by Trulaug** [comment]
adding url2=url2 did fix it but i'm now getting ApiError: Internal Server Error. Which means there is no issue in my code
